#!/usr/bin/env bash

# GPG encrypt a file
function encrypt() {
    if [ "$#" -ne 2 ]; then
        echo "Usage: encrypt <recipient> <file>"
        exit 1
    fi 
    gpg --encrypt --sign --armor -r "$1" "$2" 
}

# Reconnect WiFi & Wireguard
function wifi() {
  sudo systemctl restart connman_iwd.service
  sudo systemctl restart wg-quick@mullvad-gb14.service
}
